baseURL = 'https://datasketch.co/karisma/gobernanza-datos/'
publishDir = 'public/karisma/gobernanza-datos'
defaultContentLanguage = "es"
languageCode = 'es'
taxonomies = []
title = 'Gobernanza de datos en Colombia'
